### PR TITLE
Fix: handle author and collection filters anywhere in search string

### PR DESCRIPTION
**Pull request by mtnadi**
refs #2932

### CODE REVIEW

**Comment by mtnadi** [comment]
b80fb6a23 will hopefully make #2970 easier, but I'm not sure if things were hard-coded for performance?

**Comment by thesunshade** [comment]
> I'm not sure if things were hard-coded for performance?

I'm not 100% sure, but I believe that the code just never got refactored to include the constants. Using them is good.

**Comment by ihongda** [comment]
Thanks @mtnadi 🙏🏼

**Comment by thesunshade** [comment]
@mtnadi Thank you so much for this. I know that without this fix there would be many times people get zero results because of not using the exact format. It's really valuable. Thanks!!

**Pull request merged**
