### PR TITLE
#1790 | Purge all traces of pootle and root from sc system

### PR DESCRIPTION
**Pull request by alexander-vo**
- removed usages of po_markup and po_strings collections
- removed usages of root, root_names, root_edges
- code cleanup
#1790

### CODE REVIEW

**Comment by alexander-vo** [comment]
ok, friends!
In this PR I removed the use of `po_strings`, `po_markups`, `root`, `root_edges`, `root_names` collections
These changes 100% affected our API, some of which everyone uses
In the case of `po` - everything was removed, everything at all. The fields in the API that was 100% dependent on `po` were removed completely, those that were partially dependent were only cleaned from `po`. In either of these two cases there will definitely be some significant changes.
In case of `root` collections - I replaced them with `super_nav_details`, `super_nav_details_edges` and `names`. In the new collections we don't have all the fields that we had before, but I tried to keep the answers that we had before, but the "logical sense" of the documents may be different and corrupted
So friends, take a branch for yourself and check out what you are good at or what your work was built on once upon a time.

Waiting for your comments!

**PLEASE DON'T MERGE THIS BRANCH INTO THE MASTER UNTIL WE'RE SURE EVERYTHING IS OK HERE**

Good luck! :smile_cat:

**Comment by sujato** [comment]
I'm getting a `make load-data` error"

```
8: Loading localization
ERROR:root:{'on_duplicate': 'update'}
ERROR:root:language: Document Insertion Error, [ERR: 1210]: unique constraint violated, explaination not available, you may proceed to panic and/or despair
```

:laughing:

**Comment by alexander-vo** [comment]
> I'm getting a `make load-data` error"
> 
> ```
> 8: Loading localization
> ERROR:root:{'on_duplicate': 'update'}
> ERROR:root:language: Document Insertion Error, [ERR: 1210]: unique constraint violated, explaination not available, you may proceed to panic and/or despair
> ```
> 
> laughing

@sujato fixed!

**Review by sujato — COMMENTED** [review]
Everything seems to be working fine locally.

**Pull request merged**
