### PR TITLE
Try lift main content into light DOM.

### PR DESCRIPTION
**Pull request by ihongda**
The segmented text page and legacy text page now instead of using light DOM rendering.

### CODE REVIEW

**Comment by sujato** [comment]
That's looking good, I can't see any problems!

**Comment by sujato** [comment]
So the content is still under several layers of ShadowDOM. This would explain why Weava doesn't work.

Screenshot from 2021-12-10 07-29-05

**Comment by ihongda** [comment]
Currently `sc-page-selector.js` and `sc-site-layout.js` need to be modified, but if these two files are modified, many related styles need to be adjusted. The `:host` indicator is invalid for lightDOM, so all relevant places are To be modified.

**Comment by sujato** [comment]
> The :host indicator is invalid for lightDOM, so all relevant places are To be modified.

Okay. Well, we can also take the chance to modernize our CSS, ensure that we use `return css` rather than 

```
return html`
      <style>
```

**Comment by ihongda** [comment]
> > The :host indicator is invalid for lightDOM, so all relevant places are To be modified.
> 
> Okay. Well, we can also take the chance to modernize our CSS, ensure that we use `return css` rather than
> 
> ```
> return html`
>       <style>
> ```

According to the official document:
`The styles you add to your component are automatically scoped to the shadow root and only affect elements in the component's shadow root.`

So,  if change to light DOM rendering, the style sheet needs to be moved out of `return css`

**Comment by ihongda** [comment]
Bhante @sujato 
The `sc-site-layout.js`, `sc-page-selector.js`, 'sc-text-page-selector.js' has been instead of Light DOM rendering.
Everything seems to be normal,
If there is no problem, I will rewrite all static pages.

**Comment by sujato** [comment]
I've tested it, it looks just fine, and Weava works! So yes, let's go ahead.

**Review by sujato — CHANGES_REQUESTED** [review]
- The colors for the toolbar select are now fixed
- The static pages are still inside a shadowDOM.
- there are a bunch `TypeError` and `failed to fetch resource` errors

**Comment by ihongda** [comment]
There are more than 20 other static pages being modified :)

**Comment by ihongda** [comment]
1. Adjust the structure of `sc-site-layout.js`, pull away the static page navigation menu code to an independent component.
2. After adjusting the code structure, modifying the static page to Light DOM rendering will no longer affect other pages.

**Review by sujato — CHANGES_REQUESTED** [review]
Everything seems good, the pages select and work just fine. A couple of details needs attending, however.


- There are some js errors being reported in the console.
- The color definitions are being imported twice, and overridden. We should avoid this, styles should only be declared as necessary, we should not duplicate code. This problem is on the production site as well, so it is not caused by the changes. But now is a chance to fix it! 
- On the Home page, some of the styles are not being applied correctly, especially the font-family. The default should be sans-serif (defined in sc-static-home.js) but it's serif in most places. There are more subtle instances as well. See, for example, the titles on the nav cards: on production they have the correct line-height, on the lightDOM page the line-height is too big. It seems the culprit is the `sc-page-selector` styles in `sc-page-selector.js`.

Screenshot from 2021-12-21 07-11-29

**Comment by ihongda** [comment]
Strangely, after inspection, the color definition is indeed only loaded when the sc-site-layout component is loaded, and it is not loaded again elsewhere.

**Review by sujato — APPROVED** [review]
all looks good

**Pull request merged**
