### PR TITLE
Use "linear progress bar" instead of three dots. #1774

### PR DESCRIPTION
**Pull request by ihongda**

### CODE REVIEW

**Review by sujato — COMMENTED** [review]
I can see the loader on when I do a search. One thing, the loader should be attached to the toolbar, not in the middle of the page. I was thinking it would appear at the bottom of the toolbar, underneath the context toolbar or ATB. It should not, however, *add* height to the toolbar, but rather appear in the bottom few pixels of the toolbar.


See example here:

https://kstatic.googleusercontent.com/files/b14128fc1118df8911bb9d5405a075c013d1f060e2fee2d6d78154f0d1143b41cbf1dc31d09de993bec3b18e078e8bcd4b226b245a394e70852d20d10a45f0e3

**Comment by ihongda** [comment]
Yes, It's really better at the bottom of the toolbar :smile:

**Comment by ihongda** [comment]
The linear-progress have attached to toolbar.

**Review by sujato — APPROVED** [review]
looks good!

**Pull request merged**
