### PR TITLE
Volpage Fixes

### PR DESCRIPTION
**Pull request by chansikpark**
### Volpages in the front-end

Volume and page numbers into a physical edition ("volpage") is the preferred way to make reference to Pali texts in some academic contexts. Within Sutta Central, these references are supplied in four places (as determined by a project-wide case-insensitive search for "volpage"):

#### (1) Nerdy row of the Suttaplex card
Screenshot from 2019-11-11 06-23-52
#### (2) Nerdy row of a parallel item in the Suttaplex card (the hover needs some attention)
Screenshot from 2019-11-11 06-28-01
#### (3) Citation data copied to the clipboard using the Share function in the Suttaplex card
Screenshot from 2019-11-11 06-30-42
> Parallels for MN 2 Sabbāsava Sutta (MN i 6): AN 6.58 (AN iii 387); EA 40.6//T 125.40.6 (T ii 740a25); MA 10//T 26.10 (T i 431c13); T 31 (T i 813a05); Up 2.069 (mngon: ju 91b5 / tu 104b2); Mnd 16#217 (Mnd 444)
> Parallels for MN 2#2 Sabbāsava Sutta (MN i 6): Iti 102#2 (Iti 103); SN 12.23#1 (SN ii 29); SN 22.101#1 (SN iii 152); SN 56.25#1 (SN v 434); Kv 2.2#27 (Kv 173); Kv 2.3#16 (Kv 180)
> Parallels for MN 2#22 Sabbāsava Sutta (MN i 6): AN 4.114#9 (AN ii 116); AN 4.157#3 (AN ii 143); AN 4.165#3 (AN ii 153); AN 5.140#12 (AN iii 161); MN 125#22 (MN iii 128); pli-tv-bi-vb-pc71#2 (Vin iv 327); pli-tv-bu-vb-pc65#3 (Vin iv 129); pli-tv-kd1#439 (Vin i 1)
> Retrieved from http://localhost/mn2 on Mon Nov 11 2019 06:30:07 GMT+0900 (Korean Standard Time). 

#### (4) Right margin of text pages with textual information switched on
Screenshot from 2019-11-11 06-37-46

### Volpages in middleware

From the standpoint of the API, the endpoints that these four places use to populate volpage are:

(A) /api/suttaplex/<uid> (1)
(B) /api/parallels/<uid> (2),(3)
(C) /api/suttas/<uid> (4)

### Volpages in the database

In the case of (C), the volpages are embedded in markup strings which are found in Arango collections named `html_text` (original html markup) and `po_strings` (segmented pootle markup).

In the cases of (A) and (B), the volpages are an attribute of each Arango document from the same two collections as well as the `root` collection. These attribute-volpages represent the volume and page numbers in which the beginning of the associated text appears. When references into multiple manuscripts are available for a given text, the Suttaplex (cases (1), (2), (3)) expects the different volpage values to be concatenated with a "//". In reality, the current implementation essentially reserves "//" exclusively for Pali texts, specifically to Pali Text Society manuscripts with at most two different editions. This is to say that multiple non-Pali references and non-PTS references are unsupported. It may be preferrable going forward to revise the way volpages are stored and retrieved in order to handle multiples more robustly.

### Volpages in sc-data

The attribute-volpage values for the three collections are sourced from three different places.

The volpage attribute of `html_text` is sourced by parsing markup files in sc-data/html_text. Specifically, Mahasangiti references are plucked (eg "p_21Bu_2"), and these are converted into PTS references (suit-&-tie: eg "Bv i 1") using Pali concordance data. Currently, this applies to Khuddaka Nikaya (excluding the elder verses), Abhidhamma and Vinaya texts.

The volpage attribute of `po_strings` is sourced by parsing markup files in sc-data/po_strings. Here, the PTS references embedded in the markup are plucked and used directly (jeans-&-tshirt: eg "pts-vp-pli1.1"). Currently, this applies to the four Nikayas, the elder verses, and what appears to be much of the Vinaya.

The volpage attribute of `root` is sourced from `sutta.json`. These are in suit-&-tie format, and appears to cover all five Nikayas (imperfectly). The volpage in `root` is preferred, resorting arbitrarily either to `html_text` or `po_strings` if one isn't found there.

## Included fixes

***Updated***

Loading volpages into `html_text` is performed in `textdata.py`. Three notable changes are included:

1. An error during volpage loading would halt the entire process (solves #1518). Now, an error message is printed and loading continues.
2. Recent structural changes to the Pali concordance data required changes to adapt to the new structure (related to #1504).
3. When multiple PTS references were present, only the latest one was being used. ~~Now all of them are concatenated with "//" as expected by the front-end~~ Now all of them are returned in a map using the same keys as in `all_pali_concordance.json` (`pts-vp-pli` is assumed to mean `pts-vp-pli1ed`) (contributes to #1474).

Loading volpages into `po_strings` is performed in `po.py`. Two notable changes are included.

1. Volpages were being loaded in jeans-&-tshirt format as-is from markup. These are converted into suit-&-tie in similar manner to the conversion in `textdata.py` (solves #1353).
2. ~~"//" concatenation is adopted as opposed to the ", " concatenation that was there~~ Multiple references are returned in a map as above (contributes to #1474).

Note that the changes to `po.py` will be obsoleted by bilara. This PR replaces #1523.

Changes to suttaplex, suttaplex parallel item, suttaplex share menu were made to essentially gather all the volpage code into one place and to future-proof it a little for displaying non-PTS info.

## Miscellaneous notes

Volpages are also involved in search and text images.

In sc-data/structure/division, oddly, three dharmapadas are the only ones to include volpage (ie kn.json, sutta/dharmapadas/gdhp.json & pdhp.json).

### CODE REVIEW

**Comment by sujato** [comment]
Thanks, these fixes look awesome and should substantially improve our handling of such cases.

Regarding references for multiple editions, the notation // is a holdover from our very earliest days and should be replaced with an appropriate JSON form.

Regarding the vol/page info found in the 3 Dhammapadas, I agree this is odd. Can we move this data to a better place? This relates indirectly to #1487.

**Comment by chansikpark** [comment]
> Regarding the vol/page info found in the 3 Dhammapadas, I agree this is odd. Can we move this data to a better place? This relates indirectly to #1487.

For all of these, strictly speaking, the information is redundant since it can all be derived from `sutta.json`. The main difference is that the info in the division files are, well, per division (eg. dhp1-20 is given a vol/page reference as opposed to each of the verses having their own in `sutta.json`) And in fact, for `kn.json`, removing vol/page info improves the situation because then the suttaplex query falls back to retrieving the vol/page plucked from the markup files which has info for _both_ PTS editions.

For `pdhp`, `gdhp` and `g3dhp`, though, removing the information there would need to be accompanied either by modifications to `sutta.json` so that the respective entries are grouped up (eg. `pdhp1`,`pdhp2`... `pdhp13` => `pdhp1-13`), or the information would have to be added to the texts' markups along with a bit of code to extract it. Notably, all the `pdhp`, `gdhp` and `g3dhp` references are exactly just `Cone 1989`, `Brough 1962/2001` and `Falk 2015` respectively, without any page numbers.

The former would seem to be the correct thing to do, assuming that as per the markup, each vagga is to be treated as a single text, rather than each poem.

**Comment by sujato** [comment]
Thanks yes I agree, best to add all reference info to the relevant JSON file, rather than in the text.

For now, we do keep reference information in the HTML legacy files, but it would be easy to envisage a future where this was no longer the case; we could extract it all as we do for the segmented texts. I wouldn’t want to make this a priority at the moment, our main focus is on getting the segmented texts working properly. However for the future it may be a useful improvement.

**Comment by ihongda** [comment]
Thanks @chansikpark , 

I've reviewed the code for the front end, which looks good!
But I am not familiar with python, @blake-sc , can you help me to see the python code?

**Pull request merged**
