### PR TITLE
Fixing suttaplex API

### PR DESCRIPTION
**Pull request by alexander-vo**
- relationship edge collection now watch super_nav_details rather then root
- removed po usage for suttaplex
- `root`, `root_names`, `root_edges` usages replaced by `super_nav_details`, `names` and `super_nav_details_edges`
- new type definitions

### CODE REVIEW

**Review by sujato — COMMENTED** [review]
The suttaplex page is now showing the correct names. Problem is, that's _all_ it's showing!

Screenshot from 2021-01-21 07-13-59

**Comment by alexander-vo** [comment]
That's interesting
@ihongda can you check?

**Comment by ihongda** [comment]
> That's interesting
> @ihongda can you check?

Alex, I've found the reason
When the value of the type field changes from text to leaf, it cannot be displayed.
I will modify the corresponding front-end code :)

**Comment by alexander-vo** [comment]
Great news @ihongda !
Merge these small changes into the branch and we can send them to the master

**Pull request merged**
