### PR TITLE
Use new data sources for dictionaries.

### PR DESCRIPTION
**Pull request by ihongda**

### CODE REVIEW

**Comment by sujato** [comment]
Hongda, you may be aware of this, but just in case! 

I'm using this latest branch, and I can see the new dictionary in the lookup, so that's great. There are some issues with CSS, but I'll take care of them when you are done.

Meanwhile, in terms of content, the markup is sometimes wrong when dealing with complex entries. See here, for example, the entry for *ekaṁ*.

Screenshot from 2021-01-22 18-02-29

The words in the definitions collide together. This is because they should have separate `<li>` markup.

In the source, they are a JSON array. So the idea is that an array is an ordered list, and **each item in the array is an item in the list**.

**Comment by ihongda** [comment]
> Hongda, you may be aware of this, but just in case!
> 
> I'm using this latest branch, and I can see the new dictionary in the lookup, so that's great. There are some issues with CSS, but I'll take care of them when you are done.
> 
> Meanwhile, in terms of content, the markup is sometimes wrong when dealing with complex entries. See here, for example, the entry for _ekaṁ_.
> 
> Screenshot from 2021-01-22 18-02-29
> 
> The words in the definitions collide together. This is because they should have separate `<li>` markup.
> 
> In the source, they are a JSON array. So the idea is that an array is an ordered list, and **each item in the array is an item in the list**.

Okay, Bhante, I'll fix it :)

**Comment by ihongda** [comment]
>The words in the definitions collide together. 

Bhante, this problem has been fixed!

**Comment by sujato** [comment]
That's great, I can see the fix locally.

**Comment by ihongda** [comment]
> That's great, I can see the fix locally.
> 
> The new dictionary must be used in both the lookup and the search results, but for me I only see it in the lookup. The search results no longer have NCPED.

This is a change for lookup and I will continue to modify the search results :)

**Review by sujato — COMMENTED** [review]
It looks fine as far as I can see on the local site

**Review by alexander-vo — APPROVED** [review]
:+1:

**Review by firepick1 — APPROVED** [review]

**Pull request merged**
