### PR TITLE
Put UIDs in list authors table

### PR DESCRIPTION
**Pull request by thesunshade**
This addresses https://github.com/suttacentral/suttacentral/issues/2972

I also changed the list so that hovering over either item in the list (uid and name). It's not possible to wrap a whole row in `<a>` tags. 

Ideally I think this would be better as flexbox cells. Then it could treat whole rows as a link. 

I wrapped the UIDs in `<code>` tags. Not sure if that is the best thing to do. The point is to emphasize that that is the part that is used in the filter.

I have also added instructions and table headers.

All has been tested on my local build.

Note: For some reason the columns are not aligned properly. I'm not sure what is causing that since I didn't change any css. Perhaps it is related to the changes in the `volpage:` table?

### CODE REVIEW

**Comment by ihongda** [comment]
The display of new modifications in mobile browsers needs to be improved.

Maybe we could just keep showing the author's full name?

**Comment by thesunshade** [comment]
> The display of new modifications in mobile browsers needs to be improved.

I agree.

> Maybe we could just keep showing the author's full name?

Well, people need a way to see the UID so they can use it in the `author:` filter.

I think the problem with the mobile is mainly because the cells wrap. This was needed on the `volpage:` table but not here. If I remove the 100% width it improves:
image

**Comment by ihongda** [comment]
screenshot_2024-03-08_01-10-53

I made some modifications, using div instead of table, and made responsive optimization.

screenshot_2024-03-08_01-12-07

**Comment by thesunshade** [comment]
Looks great! Thanks!

**Pull request merged**
