### PR TITLE
Fix Chinese lookup tool.

### PR DESCRIPTION
**Pull request by ihongda**

### CODE REVIEW

**Review by sujato — COMMENTED** [review]
It works on the segmented texts, but not on the plain html texts.

Also, it lacks important functionality: the lookup should supply alternates that group characters together.

To see how it is supposed to work, see the old site: 

https://legacy.suttacentral.net/lzh/ma1

If I hover over 我聞如是 I get three results:

- 我聞如是 = "I have heard thus"
- 我聞 = "I have heard"
- 我 = "self"

This is incredibly useful! 

Now this does not happen, we only ever get a result for a single character.

**Comment by sujato** [comment]
Also, I am getting some console errors:

```
Failed to load resource: the server responded with a status of 404 (NOT FOUND)
sc-lzh2en.js?bb88:99 Uncaught TypeError: this.dictData.find is not a function
    at HTMLElement._lookupWord (sc-lzh2en.js?bb88:99)
    at HTMLElement.lookupWord (sc-lzh2en.js?bb88:66)
    at HTMLElement._setSCBottomSheet (sc-bilara-segmented-text.js?ea43:932)
    at HTMLSpanElement.word.onclick (sc-bilara-segmented-text.js?ea43:905)
/api/publication_info/ma1/lzh:1 Failed to load resource: the server responded with a status of 404 (NOT FOUND)
/api/bilarasuttas/da1/taisho?lang=lzh:1 Failed to load resource: the server responded with a status of 404 (NOT FOUND)
```

**Comment by ihongda** [comment]
> It works on the segmented texts, but not on the plain html texts.
> 
> Also, it lacks important functionality: the lookup should supply alternates that group characters together.
> 
> To see how it is supposed to work, see the old site:
> 
> https://legacy.suttacentral.net/lzh/ma1
> 
> If I hover over 我聞如是 I get three results:
> 
> * 我聞如是 = "I have heard thus"
> * 我聞 = "I have heard"
> * 我 = "self"
> 
> This is incredibly useful!
> 
> Now this does not happen, we only ever get a result for a single character.

Yes, this is very useful.

I implemented this function in the legacy text page, but the implementation mechanism of segmented text page is different from the legacy text page, so I need to find another method to deal with it :)

**Comment by ihongda** [comment]
>Also, it lacks important functionality: the lookup should supply alternates that group characters together.

Fixed!

>sc-lzh2en.js?bb88:99 Uncaught TypeError: this.dictData.find is not a function

Fixed!

**Pull request merged**
